name: Code Quality Analysis

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install backend dependencies
        working-directory: ./
        run: npm install

      - name: Run backend linter
        working-directory: ./
        run: npm run lint



  